version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  api:
    build: ${API_PATH}
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ${API_PATH}:/waldo_api/
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    ports:
      - "3000:3000"
    volumes: 
      - ./:/waldo_client
    depends_on:
      - api
volumes:
  db:
